FROM markhobson/maven-chrome:jdk-17
ARG JITSI_VERSION
# TODO remove or update on new release
RUN git clone --depth 1 --branch jitsi-meet_10066 https://github.com/jitsi/jitsi-meet-torture.git
# RUN git clone --depth 1 --branch $(echo $JITSI_VERSION | sed -r "s/[a-z]+-([0-9]+)(-[0-9]+)?/jitsi-meet_\1/") https://github.com/jitsi/jitsi-meet-torture.git
WORKDIR jitsi-meet-torture
RUN mvn install -DskipTests -Dcheckstyle.skip

ENTRYPOINT [ "mvn", "test",  "-Dchrome.enable.headless=true", "-Dchrome.disable.sandbox" ]
